"""empty message

Revision ID: b88faf5bc735
Revises: 922cbc88d53f
Create Date: 2019-03-02 13:25:37.110030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88faf5bc735'
down_revision = '922cbc88d53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chars')
    # ### end Alembic commands ###
